# Note that all path are relative to fig file
# POC config file for alpha deployements

api:
    build: ../api
    links:
        - redis:redis.dev.caliopen.org
        - cassandra:cassandra.dev.caliopen.org
        - elasticsearch:es.dev.caliopen.org

smtp:
    build: ../smtp
    ports:
        - "25:25"
        - "465:465"
    environment:
        - CALIOPEN_VIRTUAL_MAILBOX_DOMAINS=mail.caliopen.me
        - CALIOPEN_VIRTUAL_TRANSPORT=lmtp:127.0.0.1:4000
    links:
        - cassandra:cassandra.dev.caliopen.org
        - elasticsearch:es.dev.caliopen.org
    volumes:
        - ../.data/smtp/data:/var/spool/mail

redis:
    image: redis

rabbitmq:
    image: rabbitmq

cassandra:
    image: cassandra

elasticsearch:
    image: elasticsearch:1

cli:
    build: ../cli
    links:
        - redis:redis.dev.caliopen.org
        - cassandra:cassandra.dev.caliopen.org
        - elasticsearch:es.dev.caliopen.org
    volumes:
      - ./:/usr/share/caliopen/bin
    command: ['caliopen']

cassandracli:
    image: cassandra
    links:
        - cassandra:cassandra.dev.caliopen.org
    entrypoint: 'cqlsh'
    command: ['cassandra.dev.caliopen.org']

web:
  build: ../web
  ports:
    - "4000:4000"
  links:
    - api:api.dev.caliopen.org
  volumes_from:
    - web-client-ng

web-client-ng:
  build: ../web-client-ng
