#!/usr/bin/env bash


echo "This is the install script for development only"
echo "Report to README for other environment installation"

DEV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${DEV_DIR}/common.sh"

# Clone dependencies
for c in ${CALIOPEN_COMPONENTS}
do
    [[ -d "${CALIOPEN_DIR}/${c}" ]] || git clone ${BASE_URL}/caliopen.${c}.git "${CALIOPEN_DIR}/${c}"
done

echo "DONE: components have been cloned"
