#!/usr/bin/env bash

DEV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
COMPOSE_CMD="docker-compose"
CALIOPEN_BASE_DIR=/srv/caliopen/src/caliopen.base
CALIOPEN_DEV_DIR=/usr/share/caliopen/bin

cd $DEV_DIR
docker-compose run cli caliopen -f ${CALIOPEN_BASE_DIR}/caliopen.yaml.template setup
docker-compose run cli caliopen -f ${CALIOPEN_BASE_DIR}/caliopen.yaml.template create_user -e john@mail.caliopen.me -g John -f Dœuf -p 123456
docker-compose run cli caliopen -f ${CALIOPEN_BASE_DIR}/caliopen.yaml.template import -e john@mail.caliopen.me -f mbox -p "${CALIOPEN_DEV_DIR}/fixtures/john@mail.caliopen.me/mbox/"
