#!/usr/bin/env bash
# Start Caliopen service for development purpose.
# Refer to README file for further information

DEV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "${DEV_DIR}/common.sh"

WEB_DIR="${CALIOPEN_DIR}/web"
API_DIR="${CALIOPEN_DIR}/api"
VENV_DIR="${CALIOPEN_DIR}/venv"

echo "Activate virtualenv"
source "${CALIOPEN_DIR}/venv/bin/activate"

COMPOSE_CMD="docker-compose"

# Create data folders
cd "${CALIOPEN_DIR}"
[[ -d "${CALIOPEN_DIR}/.data/cassandra/data" ]] || mkdir -p "${CALIOPEN_DIR}/.data/cassandra/data"
[[ -d "${CALIOPEN_DIR}/.data/elasticsearch/data" ]] || mkdir -p "${CALIOPEN_DIR}/.data/elasticsearch/data"

# A fixed Current Working Directory is required to ensure
# data directories are always the same.
cd "${DEV_DIR}"

echo "Stop existing containers"
$COMPOSE_CMD kill

echo "Start containers"
$COMPOSE_CMD up -d redis cassandra elasticsearch api

echo "Start web server"
DEBUG=caliopen.web:* NODE_ENV=development nodemon ${WEB_DIR}/bin/start --watch ${WEB_DIR}/app
